#ifndef _ARMSYSH_CONSTANTS_H_
#define _ARMSYSH_CONSTANTS_H_

#define ARM_MCU_TYPE			"sam3x8e"

#define THREAD_STACK_OFFSET_BYTES	0x2000 // 8K
#define THREAD_PIPE_BUF_SIZE		256

#define SERIAL_RX_BUF_SIZE		32
#define SERIAL_TX_BUF_SIZE		32

#endif // _ARMSYSH_CONSTANTS_H_
